version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      prefix-development: "build"
      include: "deps"
    groups:
      # 1) PayloadCMS-specific together
      payloadcms:
        patterns:
          - "@payloadcms/**"
        update-types:
          - "patch"
          - "minor"

     # 3) all dev deps
      dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      # 3) all app deps
      dependencies:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "docker"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "ci"
    open-pull-requests-limit: 5
