import { RequiredDataFromCollectionSlug } from 'payload'

export const clinicRegistrationForm: RequiredDataFromCollectionSlug<'forms'> = {
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you for submitting your clinic registration!',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'We have received your clinic registration and will review it shortly. You will be contacted once the review is complete.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  emails: [
    {
      emailFrom: '"FindMyDoc Platform" <noreply@findmydoc.com>',
      emailTo: '{{email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Dear {{firstName}} {{lastName}},',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Thank you for registering {{clinicName}} with FindMyDoc. We have received your registration and our team will review it within 2-3 business days.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'We will contact you at {{email}} or {{phoneNumber}} once the review is complete.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: 'Clinic Registration Received - {{clinicName}}',
    },
  ],
  fields: [
    {
      name: 'clinicName',
      blockName: 'clinic-name',
      blockType: 'text',
      label: 'Clinic Name',
      required: true,
      width: 100,
    },
    {
      name: 'firstName',
      blockName: 'first-name',
      blockType: 'text',
      label: 'First Name',
      required: true,
      width: 50,
    },
    {
      name: 'lastName',
      blockName: 'last-name',
      blockType: 'text',
      label: 'Last Name',
      required: true,
      width: 50,
    },
    {
      name: 'street',
      blockName: 'street',
      blockType: 'text',
      label: 'Street',
      required: true,
      width: 50,
    },
    {
      name: 'houseNumber',
      blockName: 'house-number',
      blockType: 'text',
      label: 'House Number',
      required: true,
      width: 50,
    },
    {
      name: 'zipCode',
      blockName: 'zip-code',
      blockType: 'number',
      label: 'Postal Code',
      required: true,
      width: 50,
    },
    {
      name: 'city',
      blockName: 'city',
      blockType: 'text',
      label: 'City',
      required: true,
      width: 50,
    },
    {
      name: 'phoneNumber',
      blockName: 'phone-number',
      blockType: 'text',
      label: 'Phone Number',
      required: true,
      width: 100,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email',
      required: true,
      width: 100,
    },
  ],
  redirect: undefined,
  submitButtonLabel: 'Submit Registration',
  slug: 'clinic-registration',
  title: 'Clinic Registration Form',
  createdAt: '2025-01-28T10:00:00.000Z',
  updatedAt: '2025-01-28T10:00:00.000Z',
}