#!/usr/bin/env bash
set -euo pipefail

if [[ -n "$(git status --porcelain -- src/migrations)" ]]; then
  echo "::error::Unexpected migration workspace changes before alignment check."
  git status --short -- src/migrations
  exit 1
fi

copy_only_collection_changes="$(
  git diff --unified=0 origin/main...HEAD -- src/collections \
    | awk '
      /^\+\+\+|^---|^@@/ { next }
      /^[+-]/ {
        line = substr($0, 2)
        if (line ~ /^[[:space:]]*(label|description):/ ) next
        if (line ~ /^[[:space:]]*(\/\/|\/\*|\*|)$/) next
        print
      }
    '
)"

if [[ -z "${copy_only_collection_changes}" ]]; then
  echo "Only collection labels/descriptions changed; skipping schema migration check."
  exit 0
fi

echo "Schema files changed without migration files. Running Payload migration generation check..."
pnpm run payload migrate:create ci_schema_alignment --skip-empty

pending_migration_files="$(git status --porcelain -- src/migrations)"
if [[ -z "${pending_migration_files}" ]]; then
  echo "No pending migration generated by Payload. Continuing."
  exit 0
fi

bash ./.github/scripts/ci/print-schema-debug.sh "${pending_migration_files}"

echo "::error::Schema changes require a new migration, but src/migrations/** was not included in this change."
echo "${pending_migration_files}"
exit 1
