#!/usr/bin/env bash
set -euo pipefail

if [[ -n "$(git status --porcelain -- src/migrations)" ]]; then
  echo "::error::Unexpected migration workspace changes before alignment check."
  git status --short -- src/migrations
  exit 1
fi

echo "Schema files changed without migration files. Running Payload migration generation check..."
pnpm run payload migrate:create ci_schema_alignment --skip-empty

pending_migration_files="$(git status --porcelain -- src/migrations)"
if [[ -z "${pending_migration_files}" ]]; then
  echo "No pending migration generated by Payload. Continuing."
  exit 0
fi

bash ./.github/scripts/ci/print-schema-debug.sh "${pending_migration_files}"

echo "::error::Schema changes require a new migration, but src/migrations/** was not included in this change."
echo "${pending_migration_files}"
exit 1
