
services:
  payload:
    image: node:22.14.0-alpine
    container_name: payload
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@10.9.0 --activate && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env
    stdin_open: true
    tty: true

  postgres:
    image: postgis/postgis:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: findmydoc-portal
      POSTGIS_ENABLED: 'true'
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4
      depends_on:
        - postgres
      restart: always
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@local.com
        PGADMIN_DEFAULT_PASSWORD: password
      volumes:
        - pgadmin-data:/var/lib/pgadmin
        - ./pgservers.json:/pgadmin4/servers.json

volumes:
  data:
  node_modules:
  pgadmin-data:
