import type { CollectionConfig } from 'payload'

import { hiddenSystemTextField, immutableInquiryFields } from './inquiryCommunication/common'
import { requireInquiryModerationCommand } from './inquiryModeration/common'
import { validateInquiryModerationCase } from './inquiryModeration/invariants'

const categoryOptions = [
  { label: 'Harassment or threats', value: 'harassment-threats' },
  { label: 'Spam, fraud or impersonation', value: 'spam-fraud-impersonation' },
  { label: 'Suspected illegal content', value: 'suspected-illegal-content' },
  { label: 'Privacy concern or wrong recipient', value: 'privacy-concern' },
  { label: 'Other', value: 'other' },
]

export const InquiryModerationCases: CollectionConfig = {
  slug: 'inquiryModerationCases',
  labels: { plural: 'Inquiry Moderation Cases', singular: 'Inquiry Moderation Case' },
  admin: { hidden: true, description: 'Private moderation cases for inquiry communication' },
  access: {
    admin: () => false,
    create: () => false,
    delete: () => false,
    read: () => false,
    update: () => false,
  },
  endpoints: false,
  graphQL: false,
  hooks: {
    beforeChange: [
      requireInquiryModerationCommand,
      immutableInquiryFields([
        'inquiry',
        'clinic',
        'patient',
        'conversation',
        'targetType',
        'targetId',
        'targetMessage',
        'targetAttachment',
        'reporterKind',
        'reporterPatient',
        'reporterClinicStaff',
        'reporterKey',
        'category',
        'description',
        'idempotencyKey',
        'requestHash',
      ]),
    ],
    beforeValidate: [validateInquiryModerationCase],
  },
  fields: [
    { name: 'inquiry', type: 'relationship', relationTo: 'patientClinicInquiries', required: true, index: true },
    { name: 'clinic', type: 'relationship', relationTo: 'clinics', required: true, index: true },
    { name: 'patient', type: 'relationship', relationTo: 'patients', index: true },
    { name: 'conversation', type: 'relationship', relationTo: 'inquiryConversations', required: true, index: true },
    {
      name: 'targetType',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Message', value: 'message' },
        { label: 'Attachment', value: 'attachment' },
        { label: 'Conversation', value: 'conversation' },
      ],
    },
    hiddenSystemTextField('targetId', { index: true }),
    { name: 'targetMessage', type: 'relationship', relationTo: 'inquiryMessages', index: true },
    { name: 'targetAttachment', type: 'relationship', relationTo: 'inquiryAttachments', index: true },
    {
      name: 'reporterKind',
      type: 'select',
      required: true,
      options: [
        { label: 'Patient', value: 'patient' },
        { label: 'Clinic staff', value: 'clinic' },
      ],
    },
    { name: 'reporterPatient', type: 'relationship', relationTo: 'patients', index: true },
    { name: 'reporterClinicStaff', type: 'relationship', relationTo: 'clinicStaff', index: true },
    hiddenSystemTextField('reporterKey', { index: true, required: false }),
    { name: 'category', type: 'select', required: true, options: categoryOptions },
    { name: 'description', type: 'textarea', maxLength: 1_000 },
    hiddenSystemTextField('idempotencyKey', { index: true }),
    hiddenSystemTextField('requestHash'),
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'open',
      index: true,
      options: [
        { label: 'Open', value: 'open' },
        { label: 'Decided', value: 'decided' },
        { label: 'Appealed', value: 'appealed' },
        { label: 'Resolved', value: 'resolved' },
      ],
    },
    { name: 'accessExpandedAt', type: 'date' },
    { name: 'accessExpandedBy', type: 'relationship', relationTo: 'platformStaff' },
    { name: 'accessExpansionReason', type: 'textarea', maxLength: 500 },
    {
      name: 'decisionOutcome',
      type: 'select',
      options: [
        { label: 'No action', value: 'no-action' },
        { label: 'Content restricted', value: 'content-restricted' },
        { label: 'Conversation restricted', value: 'conversation-restricted' },
        { label: 'Identity messaging suspended', value: 'identity-messaging-suspended' },
      ],
      index: true,
    },
    { name: 'decisionCategory', type: 'select', options: categoryOptions },
    { name: 'decisionReason', type: 'textarea', maxLength: 1_000 },
    { name: 'decisionBy', type: 'relationship', relationTo: 'platformStaff' },
    { name: 'decisionAt', type: 'date', index: true },
    { name: 'effectiveUntil', type: 'date', index: true },
    { name: 'measureEndedAt', type: 'date', index: true },
    {
      name: 'affectedActorKind',
      type: 'select',
      options: [
        { label: 'Patient', value: 'patient' },
        { label: 'Clinic staff', value: 'clinic' },
      ],
    },
    { name: 'affectedPatient', type: 'relationship', relationTo: 'patients', index: true },
    { name: 'affectedClinicStaff', type: 'relationship', relationTo: 'clinicStaff', index: true },
    { name: 'appealText', type: 'textarea', maxLength: 1_000 },
    {
      name: 'appealActorKind',
      type: 'select',
      options: [
        { label: 'Patient', value: 'patient' },
        { label: 'Clinic staff', value: 'clinic' },
      ],
    },
    { name: 'appealPatient', type: 'relationship', relationTo: 'patients' },
    { name: 'appealClinicStaff', type: 'relationship', relationTo: 'clinicStaff' },
    { name: 'appealedAt', type: 'date', index: true },
    {
      name: 'appealOutcome',
      type: 'select',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Upheld', value: 'upheld' },
        { label: 'Overturned', value: 'overturned' },
      ],
    },
    { name: 'appealDecisionReason', type: 'textarea', maxLength: 1_000 },
    { name: 'appealDecidedBy', type: 'relationship', relationTo: 'platformStaff' },
    { name: 'appealDecidedAt', type: 'date', index: true },
    { name: 'finalOutcomeAt', type: 'date', index: true },
    { name: 'retentionPolicyVersion', type: 'text', index: true, admin: { hidden: true, readOnly: true } },
    { name: 'retentionReviewDueAt', type: 'date', index: true, admin: { hidden: true, readOnly: true } },
    { name: 'eventSequence', type: 'number', required: true, min: 1, defaultValue: 1 },
  ],
  indexes: [{ fields: ['reporterKey', 'idempotencyKey'], unique: true }],
  timestamps: true,
  trash: true,
}
