export * from './Features'
export * from './Process'
export * from './Categories'
export * from './Team'
export * from './Testimonials'
export * from './Pricing'
export * from './Blog'
export * from './Contact'
