name: pr-title

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited

permissions:
  pull-requests: write

jobs:
  main:
    name: lint-pr-title
    runs-on: ubuntu-24.04
    if: github.event.pull_request.base.ref == 'main'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          scopes: |
            admin
            api
            auth
            cli
            clinics
            doctors
            treatments
            reviews
            patients
            medical-specialties
            accreditation
            countries
            cities
            forms
            search
            redirects
            db
            ui
            components
            collections
            migrations
            payload
            docker
            vercel
            deps
            deps-dev

          # Disallow uppercase letters at the beginning of the subject
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Pull Request titles must follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and have valid scopes.

            ${{ steps.lint_pr_title.outputs.error_message }}

            ```
            feat(clinics): add clinic search functionality
            ^    ^        ^
            |    |        |__ Subject
            |    |___________ Scope
            |________________ Type
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true